[package]
name = "pdmotor"
edition = "2021"
version = "1.0.0"
description = "Dead simple library to connect and control a PDMOVIE Motor Mini using BLE"
readme = "README.md"
repository = "https://github.com/Av32000/pdmotor"
keywords = ["pdmovie", "follow-focus", "camera"]
license = "Unlicense"

[dependencies]
anyhow = "1.0.104"
bluer = { version = "0.17.4", features = ["bluetoothd"] }
futures-util = "0.3.34"
tokio = "1.53.1"
uuid = "1.26.1"
